### ISSUE TITLE
chapter1 채점 요청

### ISSUE THREAD

**Issue by cg-1119** [Coppermine-SP/aspdotnet_study#1]
채점 요청합니다.

**Comment by Coppermine-SP** [comment]
1번과 2번, 4번 내용은 적절하게 작성되었습니다.

3번은 SignalR이 구체적으로 어떠한 곳에서 사용하고, 클라이언트와 어떤 방식으로 통신하는지 서술하였으면 완벽한 답변이 되었을 것입니다.

5번 문제의 경우에는 제 의도는 프로젝트를 처음 생성하고, Bootstrap 5를 사용하여 기본적인 HTML 스타일링을 해보라는 의도였습니다. 제 의도와는 약간 벗어났지만, 클라이언트-사이드 라이브러리를 설치하고 레이저 문법을 시도해본 것, Layout 을 수정해본 점을 보았을때 Razor Template Engine에 대해 어느 정도 이해한 것으로 사료됩니다.

다음에 채점 요청을 보내실 때에는 반드시 라벨을 달아 주십시오.,

수고하셨습니다.
