### ISSUE TITLE
Chapter2 과제 채점 요청

### ISSUE THREAD

**Issue by cg-1119** [Coppermine-SP/aspdotnet_study#2]
과제 채점을 요청합니다.

**Comment by Coppermine-SP** [comment]
학생 모델은 올바르게 정의되었습니다. 나이와 키가 음수가 될 수 없다는 점을 고려하여 uint로 정의한 부분이 인상적입니다. 하지만 Gender가 Male, Female 두 가지 옵션만 존재한다면, string이 아닌 enum으로 정의하는 것이 데이터 정합성을 더욱 확고하게 하는 방안이 될 수 있습니다.

사용자로부터 HTML Form을 통해 입력을 받아 유효성을 검증하고 이를 모델로 만드는 부분도 잘 작성되었습니다. Controller가 동적으로 모델 클래스를 생성 할 수 있다는 것을 올바르게 이해하고 있는 것 같습니다.

사용자의 입력을 통해 생성된 모델을 Console에 출력하는 부분을 새 View를 생성하여 모델을 넘겨 표시하게 한 점도 인상적입니다.
View는 올바르게 모델을 정의하였으며 (model WebApplication1.Models.Student) , 모델에서 데이터를 가져오기 위한 Razor 문법도 올바르게 작성되었습니다.

페이지 전체적으로 Bootstrap 스타일을 올바르게 사용하였으며, Controller와 View의 구현도 올바릅니다.
수고하셨습니다.
