### ISSUE TITLE
Chapter 3 채점 요청

### ISSUE THREAD

**Issue by cg-1119** [Coppermine-SP/aspdotnet_study#3]
채점 요청 부탁드립니다.
변경사항에 궁금점이 있으시면 질문 부탁드리겠습니다.

**Comment by Coppermine-SP** [comment]
### 코멘트
1번 문항의 느슨한 결합이 필요한 이유로 제시한 메모리 효율성이 떨어지는 문제는 적절하지 않습니다. 느슨한 결합과 메모리 효율성은 서로 크게 관련이 없습니다. 의존성 주입이 필요한 이유에 대해서는 코드의 재활용성과 이식성을 중점으로 설명하지 않은 점이 아쉬운 부분입니다.

2번 문항에서 GET과 POST 요청을 비교한 것은 적절하였습니다. POST 요청의 body가 무조건 안전하지 않기 때문에 암호화 (HTTPS)가 필요하다는 점도 잘 지적하였습니다.

3번 문항의 CSRF에 대한 설명과 ASP.NET에서 CSRF에 대응하는 방법에 대하여 잘 서술하였습니다.

**4번 문제에 대한 코멘트는 아래와 같습니다:**
- 학생 모델과 DbContext를 올바르게 정의하였고, 시작 시에 올바르게 DbContext 의존성을 주입하고 있습니다.
- EF Core의 데이터베이스 공급자로 올바르게 InMemoryDatabase를 사용하고 있습니다.
- 컨트롤러는 올바르게 요구된 명세를 구현하고 있습니다.
- POST 요청에서 AntiForgeryToken을 올바르게 사용하고 있습니다.
- View가 올바른 Bootstrap 형식을 사용하고 있으며, 올바른 Razor 문법으로 모델의 데이터를 출력하고 있습니다.
- Details에 파라미터로 올바르지 않은 Id가 입력되어 모델이 null인 경우, 올바르게 예외 처리를 하였습니다.
- 학생 리스트를 출력하는 View의 model로 IEnumerable를 사용하는 것보다, ViewModel을 정의하는 것이 더욱 적절할 수 있습니다.

아쉬운 부분이 있지만, 전체적으로 답안이 올바르게 작성되었습니다.
수고하셨습니다.

---
### 추가 질문
**4번 문제에 대해 작성한 프로젝트에 대해 아래 물음에 답하세요.**

```
만약 명문 국립창원대학교에서 이 프로그램을 사용한다고 가정해봅시다. 
모든 졸업생과 재학생의 데이터가 입력된다고 가정하면, 레코드의 수가 매우 많아질 것입니다.

이때, 성능적으로 현재 프로젝트의 구조에서 발생할 수 있는 가장 큰 문제점은 무엇이며, 이를 해결하기 위한 구체적인 방안을 제시하세요.
```

**Comment by cg-1119** [comment]
추가 질문 답변 : 데이터가 많을 때 데이터를 모두 표기하기 힘든 문제점이 있었습니다. 이에 Index 페이지 footer 부분에 페이지 인덱스를 추가하여 문제 발생 부분을 해결하였습니다.

**Comment by Coppermine-SP** [comment]
레코드의 양이 많을 경우에는 부분범위 처리 (pagination)가 중요하다는 포인트를 잘 인지하였습니다.
수정된 프로젝트의 pagintation은 올바르게 구현되었습니다. 다만 파라미터로 실제 페이지를 초과하는 입력이 들어올 경우에 명시적으로 오류를 발생시키는 것이 더욱 적절할 수 있습니다.

수고하셨습니다.
