### ISSUE TITLE
Chapter 4 채점 요청

### ISSUE THREAD

**Issue by cg-1119** [Coppermine-SP/aspdotnet_study#4]
4장 과제 채점 요청합니다.

**Comment by Coppermine-SP** [comment]
페이지 전체적인 디자인은 개선 할 여지가 많아 보이지만, 전체적인 틀로 보았을때는 나쁘지 않아 보입니다. 또한 data-bs-theme 속성을 통해 색상 테마를 제공한 것은 인상적입니다. 우리가 프론트엔드와 디자인 중심적인 클래스가 아니므로, 디자인에 대한 상세한 지적이나 평가는 생략하도록 하겠습니다. 

**아래는 각 기능에 대한 자세한 평가입니다:**
### 포스트 기능
먼저 모델은 올바르게 작성되었습니다. 단 제목 속성이 nullable이고 컨트롤러에서 제목이 없는 글을 표시할 때, 올바르게 핸들링하지 않았습니다. 글을 작성 할 때에 제목을 입력 하지 않으면 글 목록에서 해당 글에 엑세스 할 수 없습니다.
이를 제목 속성을 null 허용하지 않거나, 글 목록에서 제목이 없는 글에 대해 (제목 없음)등으로 표시하는 방법으로 해결 할 수 있습니다.

Detail 메서드에서 일치하는 포스트가 없을 때 NotFound()를 리턴하여 적절하게 처리한 것은 올바릅니다. 하지만 null을 비교할때 == 보다 is 연산자를 사용하는 것이 권장됩니다. 또한 AntiForgeryToken을 적절하게 사용하여 CSRF 공격에 올바르게 대응하였습니다.
또한 글 목록 페이징 처리의 구현도 올바릅니다.

### 인증 기능
올바르게 프로그램 시작시에 인증 서비스를 의존성 주입하고 있으며, AuthController에서 올바르게 로그인과 로그아웃 처리를 핸들링하고 있습니다. 단 세션 서비스를 주입 할 때, 클라이언트에 의한 쿠키 변조를 방지하기 위하여 쿠키에 HttpOnly 옵션을 부여하는 것 (options.Cookie.HttpOnly)이 강력하게 권장됩니다. 코드에 해당 부분이 존재하지만 주석 처리되어있는 점이 상당히 아쉬운 점입니다.

사용자 인증 부분도 단순히 string을 비교하는 것보다 데이터베이스를 통해 사용자를 인증하는 방식으로 구현했으면 프로젝트의 완성도가 더욱 향상될 수 있습니다. 

각 페이지에 적절하게 Authorize Attribute를 사용하여 권한이 필요한 페이지를 구분하고 있습니다.

### 종합 평가
각 기능에 구현에는 문제가 없지만, 충분히 개선할 여지가 있어보입니다. 위의 지적 사항과 디자인 및 샘플 데이터 부분에 있어서 더욱 노력하면 더욱 완성도 높은 프로젝트를 구현 할 수 있을 것으로 사료됩니다.

수고하셨습니다.
